// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-UvW8b6jZMmON9-Jta-0I4bwEGnVOT8',
    appId: '1:593156832243:web:1668478d8c8fa6212f7086',
    messagingSenderId: '593156832243',
    projectId: 'notes-app-42352',
    authDomain: 'notes-app-42352.firebaseapp.com',
    storageBucket: 'notes-app-42352.appspot.com',
    measurementId: 'G-S570WSZJRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgI3IpVI2SfXs6FrDEdd5rs5XvupE1qaU',
    appId: '1:593156832243:android:6699b7f728c5f18a2f7086',
    messagingSenderId: '593156832243',
    projectId: 'notes-app-42352',
    storageBucket: 'notes-app-42352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVjgJ6_l8fKoxUSicia1T9dB3URb8T0FY',
    appId: '1:593156832243:ios:b86be6a9590a53992f7086',
    messagingSenderId: '593156832243',
    projectId: 'notes-app-42352',
    storageBucket: 'notes-app-42352.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVjgJ6_l8fKoxUSicia1T9dB3URb8T0FY',
    appId: '1:593156832243:ios:b86be6a9590a53992f7086',
    messagingSenderId: '593156832243',
    projectId: 'notes-app-42352',
    storageBucket: 'notes-app-42352.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK-UvW8b6jZMmON9-Jta-0I4bwEGnVOT8',
    appId: '1:593156832243:web:9e8bdf704e629a292f7086',
    messagingSenderId: '593156832243',
    projectId: 'notes-app-42352',
    authDomain: 'notes-app-42352.firebaseapp.com',
    storageBucket: 'notes-app-42352.appspot.com',
    measurementId: 'G-1W652XMGGV',
  );
}
